import { NextPage } from "next";
import { Head } from "next/document";
import ActionCall from "../../components/homepage/actionCall";
import Body from "../../components/homepage/layout/body";
import Layout from "../../components/layout/layout";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";
import client from "../../apollo-client";
import { allProducts } from "../../queries";

const Product: NextPage = ({ product }: any) => {
  const {
    id,
    attributes: {
      Price,
      ProductName,
      Description,
      designer: {
        data: {
          attributes: { Designer },
        },
      },
      product_type: {
        data: {
          attributes: { ProductType },
        },
      },
      Images: { data: imageDataArr },
    },
  } = product;

  const {
    attributes: { url: coverImage },
  } = imageDataArr[0];

  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
       */}
      <Layout>
        <Body />
      </Layout>
    </div>
  );
};

export const getServerSideProps = async (context: any) => {
  const { id } = context.query;

  const { data } = await client.query({
    query: allProducts(`filters: {id: {eq: ${id}}},`),
  });

  return {
    props: {
      product: data.products.data,
    },
  };
};

export default Product;
